### ISSUE TITLE
小果-Running Everyday-Part One(10.26-11.25)

### ISSUE THREAD

**Issue by imsobear** [imsobear/Done-Everyday#1]
- 目标：坚持30天；每天不少于3km；速度提升到 5min/km 以内。
- 奖品：送自己一个机械键盘，或者耳机，或者其他千元以内的数码产品。
- 惩罚：请 issue#3(@ynliSonia) 的同学吃好吃的。
- 备注：如果某天有剧烈运动如打球爬山之类的，或者是天气状况很差，则跑步取消，不计入惩罚范围内。

**Comment by imsobear** [comment]
## Day one(10.26):

### Listen:

《银河护卫队》电影原声。

### Think：

突然想去跑步，跑步的时候有了 `Running Everyday` 这个想法，然后就是构思，最终的成果就是 README 里的nei内容了。

还有，周末看了三部电影：《大话西游之大圣娶亲》、《放牛班的春天》、《忠犬八公的故事》，除了《放牛班的春天》是第一次看，其他都是第 N 遍了。

《放牛班的春天》与《死亡诗社》，很类似的电影：一群处在不同年龄段的学生，但同样叛逆、同样跟大人的世界格格不入然后被误解，一位独特有个性的老师，音乐老师马修以及我们熟知的 Captain，最后的结局都不尽完美或者略带悲伤...

《忠犬八公的故事》，自然还是一如既往的感人，不过觉得突兀的是教授的去世太过突然也没有过多的交待，当然这都不是重点，重点是 `hachi`，之前很羡慕别人的项目总有一个很感性的名字：totoro, Walt...那么有机会的话~

### Evidence：

使用的是「咕咚」这个 APP 记录的：

[跑步路线速度时间记录](https://cloud.githubusercontent.com/assets/2505411/4783338/4da0b286-5d22-11e4-979d-c8379729707c.jpg)

**Comment by imsobear** [comment]
## Day 2(10.27)

### Listen:

some music~

### Think:

想了一些 `webdriver` 的问题，一些业务的问题~

### Evidence:

[跑步路线速度时间记录](https://cloud.githubusercontent.com/assets/2505411/4793642/7ccd43f8-5def-11e4-9f18-0a5b781be71d.jpg)

**Comment by imsobear** [comment]
## Day 3(10.28)

### Listen:

poadcast: 太医来了，[走进莆田系－－私立医院黑幕大起底](http://ipn.li/taiyilaile/6/)

### Think:

>  在听 poadcast 的过程中，又再次感受到了百度的竞价排名有多么的无良与作恶。作为国民基础的医疗行业，本身由于资源不对等、百姓对医疗知识的缺失等种种原因造成了各种不便，人民就医难、对医生的信任缺失、医患关系的日趋紧张，私立医院对利益的贪婪，而百度的竞价排名为这种贪婪提供了一个途径，从中牟取利益，当然需要记住的是：医疗只是一方面，而百度的竞价排名涵盖了生活的方方面面。

### Evidence:

[跑步路线速度时间记录](https://cloud.githubusercontent.com/assets/2505411/4811770/93d1d406-5ebc-11e4-9973-676ab4c00ef2.jpg)

**Comment by imsobear** [comment]
## Day 4-6(10.29-10.31)

杭州连续下雨，跑步暂停，跟同事一块去了健身房两次，健身计划也就慢慢起步啦。

最近参加了「百年阿里」的培训，另一方面正式入职三个月要进行转正述职，所以有两大段要说的话，今晚整理。
1. 我的百阿感想
2. 这三个月的所做所想

今天晚上目测可以去跑个步了，话说一边进行着自己的跑步计划，另一边读着村上的《跑步时我在想什么》，生活还蛮有趣的不是(>﹏<)

**Comment by imsobear** [comment]
## Day 7(11.1)

晚上回家晚了，因此跑步就搁浅了，惩罚一次:cry:

**Comment by imsobear** [comment]
## Day 8(11.2)

打了两个小时的篮球，腰疼...腰~

**Comment by imsobear** [comment]
## Day 9(11.3)

此刻我还在纠结要不要去跑步...shit

**Comment by DarkKate** [comment]
= =
